
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["k8s.io/kubernetes/pkg/kubectl/cmd/util"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/PuerkitoBio/purell"
  revision = "b938d81255b5473c57635324295cb0fe398c7a58"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  revision = "7524189396c68dc4b04d53852f9edc00f816b123"

[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "996760c56486beb81e91bb7bdb816f8c6f29284e"

[[constraint]]
  name = "github.com/google/go-jsonnet"
  revision = "v0.11.2"

[[constraint]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"

[[constraint]]
  name = "github.com/ksonnet/ksonnet-lib"
  version = "v0.1.11"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "8382b23d18dbaaff8e5f7e83784c53ebb8ec2f47"

[[constraint]]
  name = "github.com/onsi/gomega"
  revision = "c893efa28eb45626cdaa76c9f653b62488858837"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "778f2e774c725116edbc3d039dc0dfc1cc62aae8"

[[constraint]]
  name = "github.com/spf13/afero"
  revision = "9be650865eab0c12963d8753212f4f9c66cdcf12"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "v1.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  source = "github.com/shomron/pflag"
  revision = "fix-unknown-flag-panic"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "f6abca593680b2315d2075e0f5e2a9751e3f431a"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "cce311a261e6fcf29de72ca96827bdb0b7d9c9e6"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "eb3733d160e74a9c7e442f435eb3bea458e1d19f"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

# required by client-go v7.0.0
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v9.8.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.10.4"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.9.1"

[[constraint]]
  name = "github.com/GeertJohan/go.rice"
  revision = "c02ca9a983da5807ddf7d796784928f5be4afd09"

[[override]]
  name = "github.com/go-openapi/spec"
  revision = "bcff419492eeeb01f76e77d2ebc714dc97b607f5"

[[constraint]]
  name = "github.com/go-openapi/validate"
  source = "github.com/heptio/validate"
  branch = "support-int-or-string"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[override]]
  name = "github.com/docker/docker"
  revision = "04864cb3cb526ddeee70dc6e17a6c7802ef91a0b"

[[constraint]]
  branch = "master"
  name = "github.com/shazow/go-diff"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[override]]
  name = "github.com/json-iterator/go"
  version =  "1.1.3"

